language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - CMAKE_BUILD_TYPE=Release  DEMO=screen-aligned-triangle
    - CMAKE_BUILD_TYPE=Debug    DEMO=screen-aligned-triangle

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-add-repository ppa:cginternals/backports-ppa -y ;
      sudo apt-get update -qq ;
      sudo apt-get install -qq cmake libgl1-mesa-dev mesa-common-dev clang-tidy-3.8 libglbinding-dev libxrandr-dev;
    fi
  - git clone https://github.com/g-truc/glm.git ;
    cd glm ;
    pwd ;
    git checkout tags/0.9.8.5 ;
    cmake . -DCMAKE_INSTALL_PREFIX=. ;
    cmake --build . --target install;
    cd ..
  - git clone https://github.com/glfw/glfw.git ;
    cd glfw ;
    pwd ;
    git checkout tags/3.2.1 ;
    cmake . -DCMAKE_INSTALL_PREFIX=. ;
    cmake --build . --target install;
    cd ..

script:
  - pwd
  - cd $DEMO
  - mkdir build
  - cd build 
  - pwd
  - cmake .. -DCMAKE_PREFIX_PATH=../glm;../glfw;
  - cmake --build .

