language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc
  # clang

env:
  matrix:
    - CMAKE_BUILD_TYPE=Release  DEMO=screen-aligned-triangle
    # CMAKE_BUILD_TYPE=Debug    DEMO=screen-aligned-triangle

before_install:
  # c++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # 3rdp
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-add-repository ppa:cginternals/backports-ppa -y ;
      sudo apt-get update -qq ;
    fi
  # glm 0.9.8.5 - not required yet
  # git clone https://github.com/g-truc/glm.git ;
  # glfw3 3.2.1
  - sudo apt-get install -qq libxrandr-dev libxinerama-dev libxcb-xkb-dev libxcursor-dev ;
    git clone https://github.com/glfw/glfw.git ;
    
install: 
  # c++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # 3rdp
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get install -qq cmake libgl1-mesa-dev mesa-common-dev clang-tidy-3.8 libglbinding-dev;
    fi
  # glm 0.9.8.5 - not required yet
  # cd glm ;
  # git checkout tags/0.9.8.5 ;
  # cmake . -DCMAKE_INSTALL_PREFIX=. ;
  # cmake --build . --target install;
  # cd ..
  # glfw3
  - cd glfw ;
    git checkout tags/3.2.1 ;
    cmake . -DCMAKE_INSTALL_PREFIX=. -DGLFW_BUILD_EXAMPLES=Off -DGLFW_BUILD_TESTS=Off -DGLFW_BUILD_DOCS=Off -DGLFW_VULKAN_STATIC=Off ;
    cmake --build . --target install ;
    cd ..

script:
  - cd $DEMO
  - mkdir build
  - cd build 
  # cmake .. -DCMAKE_PREFIX_PATH="$PWD/../../glm;$PWD/../../glfw"
  - cmake .. -DCMAKE_PREFIX_PATH="$PWD/../../glfw"
  - cmake --build .

