language: cpp

sudo: required
dist: trusty

os:
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - CMAKE_BUILD_TYPE=Release  DEMO=screen-aligned-triangle
    - CMAKE_BUILD_TYPE=Debug    DEMO=screen-aligned-triangle

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-add-repository ppa:cginternals/backports-ppa -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq cmake libgl1-mesa-dev mesa-common-dev libglfw3-dev clang-tidy-3.8 libglm-dev libglbinding-dev ; fi

before_script:
  - cd $DEMO
  - mkdir build
  - cd build 

script:
  - cmake ..
  - cmake --build 

